### ISSUE TITLE
Overridden jQuery.fn.html() raises error when passed an empty string

### ISSUE THREAD

**Issue by elijahr** [ehynds/jquery-create-event#1]
Usually, calling jQuery('.foo').html('') will remove all child nodes from the .foo nodes in the DOM.  However, using jquery.create.js, an error is thrown:

```
fileName: "/media/js/jquery.create.js"
lineNumber: 61
message: "node[0] is undefined"
name: "TypeError"
stack: "walk()@......."
```

Replacing:
            node = $(nodes[i]);

with:
            node = $(nodes[i]);
            if (node.length == 0){
                continue;
            }

seemed to take care of it.

**Comment by ehynds** [comment]
fixed ee08a718bf3cf7ca83a184e62673efe6fc837b17
